blob_container:
  train_data: climate-train-data
  logs: climate-logs

log_dir: logs

data_dir:
  train_good: good/train

log: 
  data_transform: train_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_log.txt
