blob_container:
  io_files: climate-io-files
  logs: climate-logs
  feature_store: climate-feature-store

files:
  train_input: train_input_file.csv
  train_input_preprocess: train_input_file_preprocess.csv
  null_values: null_values.csv
  train_file: trainictions.csv

target_col: Output

model_dir:
  prod: production

log:
  preprocess_train: preprocess_train_log.txt
  upload: upload_preprocessing_train_log.txt

knn_imputer:
  n_neighbors: 3
  weights: uniform

log_dir: preprocess_train_logs

pca_model:
  n_components: 100
