blob_container:
  io_files: climate-io-files-03e0100
  logs: climate-logs-4e1f3bd
  feature_store: climate-feature-store-02126f6

files:
  train_input: train_input_file.csv
  train_input_preprocess: train_input_file_preprocess.csv
  null_values: null_values.csv
  train_file: trainictions.csv

target_col: Output

model_dir:
  prod: production

log:
  preprocess_train: preprocess_train_log.txt
  upload: upload_log.txt

knn_imputer:
  n_neighbors: 3
  weights: uniform

log_dir: logs

pca_model:
  n_components: 100
