base:
  random_state: 42
  test_size: 0.33

target_col: Output

blob_container:
  io_files: climate-io-files
  model: climate-model
  feature_store: climate-feature-store
  logs: climate-logs

mlflow_config:
  exp_name: climate-ops
  run_name: mlops
  serialization_format: cloudpickle

models_dir:
  train: trained

file_pattern:
  climate_features-

log:
  model_train: model_training_log.txt
  upload: upload_log.txt

log_dir: model_training_logs

model_utils:
  verbose: 3
  cv: 5
  n_jobs: -1

save_format: .sav

RandomForestClassifier:
  n_estimators:
    - 10
    - 50
    - 100
    - 130

  criterion:
    - gini
    - entropy

  max_features:
    - auto
    - log2

  max_depth:
    - 2
    - 3
    - 4
    - 5
    
XGBClassifier:
  learning_rate:
    - 0.5
    - 0.1
    - 0.01
    - 0.001

  max_depth:
    - 3
    - 5
    - 10
    - 20

  n_estimators:
    - 10
    - 50
    - 100
    - 200
