blob_container:
  io_files: climate-io-files
  logs: climate-logs
  raw_train_data: climate-raw-data
  train_data: climate-train-data

data_dir:
  raw_train_batch: train_batch
  train_good: good/train  
  train_bad: bad/train

files:
  train_schema: climate-schema_training.json
  regex: climate-regex.txt

log_dir: raw_train_data_validation_logs

log:
  upload: upload_log.txt
  raw_train_main: raw_train_main_log.txt
  values_from_schema: values_from_schema_log.txt
  general: general_log.txt
  name_validation: train_name_validation_log.txt
  col_validation: train_col_validation_log.txt
  missing_values_in_col: train_missing_values_in_column.txt