blob_container:
  io_files: climate-io-files-03e0100
  model: climate-model-3e502a3
  logs: climate-logs-4e1f3bd
  feature_store: climate-feature-store-02126f6
  component: climate-kubeflow-components-4efdbdc

files:
  features: climate_train_features.csv
  targets: climate_train_targets.csv
  elbow_plot: K-Means_Elbow_train.png

log:
  clustering: train_clustering_log.txt
  upload: upload_train_cluster_log.txt

log_dir: logs

base:
  random_state: 42

model_dir:
  trained: trained

KMeans:
  init: k-means++

max_clusters: 11

model_save_format: .sav

knee:
  curve: convex
  direction: decreasing

component: clustering_component.yaml

