blob_container:
  pred_data: climate-pred-data-2648352
  logs: climate-logs-4e1f3bd

log_dir: logs

data_dir:
  pred_good: good/pred

log: 
  data_transform: pred_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_log.txt
