blob_container:
  pred_data: climate-pred-data
  logs: climate-logs

dir:
  pred_good_data: good/pred
  log: data_transform_pred_logs

log:
  data_transform: pred_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_data_transform_pred_log.txt
