blob_container:
  pred_data: climate-pred-data
  logs: climate-logs

log_dir: data_transform_pred_logs

data_dir:
  pred_good: good/pred

log:
  data_transform: pred_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_log.txt
