blob_container:
  io_files: climate-io-files
  logs: climate-logs
  raw_pred_data: climate-raw-data
  pred_data: climate-pred-data

data_dir:
  raw_pred_batch: pred_batch
  pred_good: good/pred
  pred_bad: bad/pred

files:
  pred_schema: climate-schema_preding.json
  regex: climate-regex.txt

log_dir: raw_pred_data_val_logs

log:
  upload: upload_raw_pred_data_val_log.txt
  raw_pred_main: raw_pred_main_log.txt
  values_from_schema: values_from_schema_log.txt
  general: general_log.txt
  name_validation: pred_name_validation_log.txt
  col_validation: pred_col_validation_log.txt
  missing_values_in_col: pred_missing_values_in_column.txt
