blob_container:
  io_files: climate-io-files
  logs: climate-logs
  feature_store: climate-feature-store

files:
  pred_input: pred_input_file.csv
  pred_input_preprocess: pred_input_file_preprocess.csv
  null_values: null_values.csv
  pred_file: predictions.csv

target_col: Output

model_dir:
  prod: production

log:
  preprocess_pred: preprocess_pred_log.txt
  upload: upload_log.txt

knn_imputer:
  n_neighbors: 3
  weights: uniform

log_dir: preprocess_pred_logs

pca_model:
  n_components: 100
