log:
  pred: prediction_log.txt
  upload: upload_model_prediction_log.txt

dir:
  prod_model: production
  log: model_prediction_logs

save_format: ".sav"

files:
  pred_input_file_preprocess: pred_input_file_preprocess.csv
  pred_output: predictions.csv

blob_container:
  feature_store: climate-feature-store
  logs: climate-logs
  model: climate-model
  io_files: climate-io-files
