log:
  pred: prediction_log.txt
  upload: upload_model_prediction_log.txt

model_dir:
  prod: production

save_format: ".sav"

log_dir: model_prediction_logs

files:
  pred_input_file_preprocess: pred_input_file_preprocess.csv
  pred_output: predictions.csv

blob_container:
  feature_store: climate-feature-store
  logs: climate-logs
  model: climate-model
  io_files: climate-io-files