blob_container:
  pred_data: climate-pred-data
  logs: climate-logs
  feature_store: climate-feature-store

files:
  pred_export: pred_input_file.csv

dir:
  pred_good_data: good/pred
  log: db_operation_pred_logs

log:
  db_insert: pred_db_insert_log.txt
  export_csv: pred_export_to_csv_log.txt
  db_main: prediction_main_log.txt
  upload: upload_db_operation_pred_log.txt

mongodb:
  db_name: climate-data
  collection_name: climate-pred-data
