blob_container:
  pred_data: climate-pred-data-2648352
  logs: climate-logs-4e1f3bd
  feature_store: climate-feature-store-02126f6
  
files:
  pred_export: pred_input_file.csv

data_dir:
  pred_good: good/pred

log_dir: logs

log:
  db_insert: pred_db_insert_log.txt
  export_csv: pred_export_to_csv_log.txt
  db_main: prediction_main_log.txt
  upload: upload_log.txt

mongodb:
  db_name: climate-data
  collection_name: climate-pred-data
