blob_container:
  train_data: climate-train-data-5acbd2d
  logs: climate-logs-4e1f3bd
  feature_store: climate-feature-store-02126f6
  
files:
  train_export: train_input_file.csv

data_dir:
  train_good: good/train

log_dir: logs

log:
  db_insert: train_db_insert_log.txt
  export_csv: train_export_to_csv_log.txt
  db_main: training_main_log.txt
  upload: upload_log.txt

mongodb:
  db_name: climate-data
  collection_name: climate-train-data
